version: "3.8"

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/bitnami
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - common

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.6
    volumes:
      - kafka-data:/bitnami
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    networks:
      - common
  
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9100:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - common

  auth-db:
    container_name: auth-db
    image: postgres:13.5-alpine
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=auth_service_db
      - DB_DEFAULT_DATABASE=auth_service_db
      - DB_DEFAULT_HOST=auth-db
      - DB_DEFAULT_PORT=5432
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - common
  
  invoice-db:
    container_name: invoice-db
    image: postgres:13.5-alpine
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=invoice_service_db
      - DB_DEFAULT_DATABASE=invoice_service_db
      - DB_DEFAULT_HOST=invoice-db
      - DB_DEFAULT_PORT=54322
    volumes:
      - invoice-postgres-data:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    networks:
      - common
    
  order-db:
    container_name: order-db
    image: postgres:13.5-alpine
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=order_service_db
      - DB_DEFAULT_DATABASE=order_service_db
      - DB_DEFAULT_HOST=order-db
      - DB_DEFAULT_PORT=54323
    volumes:
      - order-postgres-data:/var/lib/postgresql/data
    ports:
      - "54323:5432"
    networks:
      - common

  api-gateway:
    container_name: api-gateway
    image: invoice_hub_microservices_api-gateway
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        NODE_PORT: 3000
        SERVICE_NAME: api-gateway
        ENV_PATH: ./deployment/dev/.env
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - common
    volumes:
      - ../../common:/app/common
      - ../../api-gateway/src:/app/api-gateway/src:delegated
    depends_on:
      - auth-db
      - invoice-db
      - order-db
      - kafka
      - order-service
      - invoice-service
      - auth-service
    command: sh -c "yarn start"
  
  auth-service:
    container_name: auth-service
    image: invoice_hub_microservices_auth-service
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        NODE_PORT: 4001
        SERVICE_NAME: services/auth-service
        ENV_PATH: ./deployment/dev/.env
    environment:
      - PORT=4001
      - POSTGRES_DB=auth_service_db
      - DB_DEFAULT_DATABASE=auth_service_db
      - DB_DEFAULT_HOST=auth-db
      - DB_DEFAULT_PORT=5432
    ports:
      - "4001:4001"
    networks:
      - common
    volumes:
      - ../../common:/app/common
      - ../../services/auth-service/src:/app/services/auth-service/src:delegated
      - ../../services/auth-service/migrations:/app/services/auth-service/migrations:delegated
    depends_on:
      - auth-db
      - kafka
      - order-service
      - invoice-service
    command: sh -c "yarn mup && yarn start"

  invoice-service:
    container_name: invoice-service
    image: invoice_hub_microservices_invoice-service
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        NODE_PORT: 4002
        SERVICE_NAME: services/invoice-service
        ENV_PATH: ./deployment/dev/.env
    environment:
      - PORT=4002
      - POSTGRES_DB=invoice_service_db
      - DB_DEFAULT_DATABASE=invoice_service_db
      - DB_DEFAULT_HOST=invoice-db
      - DB_DEFAULT_PORT=5432
    ports:
      - "4002:4002"
    networks:
      - common
    volumes:
      - ../../common:/app/common
      - ../../services/invoice-service/src:/app/services/invoice-service/src:delegated
      - ../../services/invoice-service/migrations:/app/services/invoice-service/migrations:delegated
    depends_on:
      - invoice-db
      - kafka
      - order-service
    command: sh -c "yarn mup && yarn start"
  
  order-service:
    container_name: order-service
    image: invoice_hub_microservices_order-service
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        NODE_PORT: 4003
        SERVICE_NAME: services/order-service
        ENV_PATH: ./deployment/dev/.env
    environment:
      - PORT=4003
      - POSTGRES_DB=order_service_db
      - DB_DEFAULT_DATABASE=order_service_db
      - DB_DEFAULT_HOST=order-db
      - DB_DEFAULT_PORT=5432
    ports:
      - "4003:4003"
    networks:
      - common
    volumes:
      - ../../common:/app/common
      - ../../services/order-service/src:/app/services/order-service/src:delegated
      - ../../services/order-service/migrations:/app/services/order-service/migrations:delegated
    depends_on:
      - order-db
      - kafka
    command: sh -c "yarn mup && yarn start"

networks:
  common:
    driver: bridge

volumes:
  zookeeper-data:
  kafka-data:
  auth-postgres-data:
  invoice-postgres-data:
  order-postgres-data:
