version: "3.8"

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - ./root/zookeeper-data:/bitnami
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - ${CONTAINER_NAME_PREFIX}

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.6
    volumes:
      - ./root/kafka-data:/bitnami
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    networks:
      - ${CONTAINER_NAME_PREFIX}
  
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9100:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - ${CONTAINER_NAME_PREFIX}
    
  api-gateway:
    container_name: api-gateway
    image: invoice_hub_microservices_api-gateway
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        NODE_PORT: 3000
        SERVICE_NAME: api-gateway
        ENV_PATH: ./deployment/dev/.env
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - ${CONTAINER_NAME_PREFIX}
    volumes:
      - ../../packages:/app/packages
      - ../../api-gateway/src:/app/api-gateway/src:delegated
    depends_on:
      - kafka
      - invoice-service
      - order-service
      - role-service
      - user-service
    command: sh -c "yarn start"

  invoice-service:
    container_name: invoice-service
    image: invoice_hub_microservices_invoice-service
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        NODE_PORT: 4001
        SERVICE_NAME: services/invoice-service
        ENV_PATH: ./deployment/dev/.env
    environment:
      - PORT=4001
    ports:
      - "4001:4001"
    networks:
      - ${CONTAINER_NAME_PREFIX}
    volumes:
      - ../../packages:/app/packages
      - ../../services/invoice-service/src:/app/services/invoice-service/src:delegated
    depends_on:
      - kafka
    command: sh -c "yarn start"
  
  order-service:
    container_name: order-service
    image: invoice_hub_microservices_order-service
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        NODE_PORT: 4002
        SERVICE_NAME: services/order-service
        ENV_PATH: ./deployment/dev/.env
    environment:
      - PORT=4002
    ports:
      - "4002:4002"
    networks:
      - ${CONTAINER_NAME_PREFIX}
    volumes:
      - ../../packages:/app/packages
      - ../../services/order-service/src:/app/services/order-service/src:delegated
    depends_on:
      - kafka
    command: sh -c "yarn start"

  role-service:
    container_name: role-service
    image: invoice_hub_microservices_role-service
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        NODE_PORT: 4003
        SERVICE_NAME: services/role-service
        ENV_PATH: ./deployment/dev/.env
    environment:
      - PORT=4003
    ports:
      - "4003:4003"
    networks:
      - ${CONTAINER_NAME_PREFIX}
    volumes:
      - ../../packages:/app/packages
      - ../../services/role-service/src:/app/services/role-service/src:delegated
    depends_on:
      - kafka
    command: sh -c "yarn start"

  user-service:
    container_name: user-service
    image: invoice_hub_microservices_user-service
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        NODE_PORT: 4004
        SERVICE_NAME: services/user-service
        ENV_PATH: ./deployment/dev/.env
    environment:
      - PORT=4004
    ports:
      - "4004:4004"
    networks:
      - ${CONTAINER_NAME_PREFIX}
    volumes:
      - ../../packages:/app/packages
      - ../../services/user-service/src:/app/services/user-service/src:delegated
    depends_on:
      - kafka
    command: sh -c "yarn start"

networks:
  backend:
    driver: bridge

volumes:
  zookeeper-data:
  kafka-data: