global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:4001']

  - job_name: 'invoice-service'
    static_configs:
      - targets: ['invoice-service:4002']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:4003']
